name: damaz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  collection: ^1.18.0
  flutter_credit_card: ^4.0.1
  google_nav_bar: ^5.0.6
  get: ^4.6.5
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.1
  intl: any
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  sensors_plus: ^6.1.0
  syncfusion_flutter_charts: ^27.2.4
  flutter_local_notifications: ^18.0.1
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.3.1
  geofence_service: ^6.0.0+1
  connectivity_plus: ^6.1.0
  battery_plus: ^6.2.0
  sign_button: ^2.0.6
  flutter_facebook_auth: ^7.1.1
  status_alert: ^1.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  #arb-dir: lib/l10n
  #template-arb-file: app_en.arb
  #output-localization-file: app_localizations.dart
  assets:
    - lib/images/burgers/
    - lib/images/sides/
    - lib/images/salads/
    - lib/images/drinks/
    - lib/images/desserts/
    - lib/images/apple_logo.png
    - lib/images/google_logo.png
    - lib/images/gpsIcon.png
    - lib/images/motionIcon.png
    - lib/images/air-conditioner.png
    - lib/images/light-bulb.png
    - lib/images/menu.png

dependency_overrides:
  flutter_plugin_android_lifecycle: "any"
